#!/bin/sh
#PBS -l nodes=4,walltime=00:10:00
#PBS -q cpa
#PBS -d .
cat $PBS_NODEFILE


 mpiexec -np 1 ./practica_slepc ringhals1.petsc -eps_nev 6 -eps_view_values
 mpiexec -np 2 ./practica_slepc ringhals1.petsc -eps_nev 6 -eps_view_values
 mpiexec -np 4 ./practica_slepc ringhals1.petsc -eps_nev 6 -eps_view_values
 
 
 mpiexec -np 1 ./practica_slepc ringhals2.petsc -eps_nev 6 -eps_view_values
 mpiexec -np 2 ./practica_slepc ringhals2.petsc -eps_nev 6 -eps_view_values
 mpiexec -np 4 ./practica_slepc ringhals2.petsc -eps_nev 6 -eps_view_values

 