#!/bin/sh
#PBS -l nodes=4,walltime=00:10:00
#PBS -q cpa
#PBS -d .
cat $PBS_NODEFILE


mpirun -np 4 ./svd64 -fileA /scratch/mnichipr/A64_30.petsc -fileG /scratch/mnichipr/b64_30_forbild.petsc  -svd_nsv 4096
