version: '2'
services:
    registry:
        restart: always
        image: registry:2
        ports:
            - 5000:5000
        volumes:
            - "faasRegistry:/var/lib/registry"
    broker:
        build: ./broker/
        image: brokerfaas
        environment:
        - ZMQ_BIND_ADDRESS=tcp://*:2000
        ports:
        - 3333:3333
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        links:
        - registry
    worker:
        build: ./worker/
        image: workerfaas
        environment:
        - ZMQ_CONN_ADDRESS=tcp://broker:2000
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/tmp/requests:/worker/requestsworker"
        links:
        - broker
volumes:
  faasRegistry:
